version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: gomod
  directory: "/cmd/example"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/krzysztofreczek/go-structurizr
    versions: "=0.0.0"
    
- package-ecosystem: gomod
  directory: "/cmd/example-yaml"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/krzysztofreczek/go-structurizr
    versions: "=0.0.0"
