repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0  # Reemplaza con la versión válida
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
