version: '3'

tasks:
  download_all_deps:
    - go mod download
    - cd cmd/example && go mod download
    - cd cmd/example-yaml && go mod download

  test:
    cmds:
      - go test -v ./...

  test_examples:
    cmds:
      - cd cmd/example && sh example.sh --test
      - cd cmd/example-yaml && sh example.sh --test

  build:
    cmds:
      - go build ./...

  build_examples:
    cmds:
      - cd cmd/example && sh example.sh
      - cd cmd/example-yaml && sh example.sh
