version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test -race -v ./...

  test_examples:
    cmds:
      - cd cmd/example && sh example.sh --test
      - cd cmd/example-yaml && sh example.sh --test

  build:
    cmds:
      - go build ./...

  build_examples:
    cmds:
      - cd cmd/example && sh example.sh
      - cd cmd/example-yaml && sh example.sh

  update_examples:
    cmds:
      - cd cmd/example && go get -u ./... && go mod tidy
      - cd cmd/example-yaml && go get -u ./... && go mod tidy
